add dependabot.yml to check the component version upgrades automatica…
resteasy/resteasy-spring pull request #62
Opened 2022-11-16 14:05 UTC by liweinan

…lly.

2022-11-16 14:15 UTC, liweinan commented
After this work it done at `resteasy-spring`, I'll do the setup for `resteasy-spring-boot`.

2022-11-16 16:08 UTC, jamezp requested changes
There is a chance you need to review the dependencies in the POM's to ensure we ignore any that we don't want to use the latest for. I didn't see any at first glance, but we might just want to make sure.

2022-11-16 16:08 UTC, jamezp commented on .github/dependabot.yml
> +        update-types: ['version-update:semver-major', 'version-update:semver-minor']
I don't see a dependency on any of these in the POM's.

2022-11-16 16:24 UTC, liweinan commented
@jamezp Thanks for checking! I'll modify this file according to `resteasy-spring` usage.

2023-01-25 15:58 UTC, liweinan commented
@jamezp I have removed the unnecessary ignores sections. I guess this is a basic setup now, and if there are more requirements I can tweak it further, wdyt?

2023-01-25 16:01 UTC, jamezp approved these changes
Looks good to me. If there are things we don't want to upgrade in the future we can add it to the ignore list.

2023-01-25 16:55 UTC, liweinan commented
@jamezp yes sir!

2023-01-25 16:55 UTC, merged